/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<
      'root',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '$error': RouteRecordInfo<
      '$error',
      '/:error(.*)',
      { error: ParamValue<true> },
      { error: ParamValue<false> },
      | never
    >,
    'balances': RouteRecordInfo<
      'balances',
      '/balances',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'companies': RouteRecordInfo<
      'companies',
      '/companies',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'control': RouteRecordInfo<
      'control',
      '/control',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'customers': RouteRecordInfo<
      'customers',
      '/customers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard': RouteRecordInfo<
      'dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard-crm-active-project': RouteRecordInfo<
      'dashboard-crm-active-project',
      '/dashboard/CrmActiveProject',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard-crm-activity-timeline': RouteRecordInfo<
      'dashboard-crm-activity-timeline',
      '/dashboard/CrmActivityTimeline',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard-crm-analytics-sales': RouteRecordInfo<
      'dashboard-crm-analytics-sales',
      '/dashboard/CrmAnalyticsSales',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard-crm-earning-reports-yearly-overview': RouteRecordInfo<
      'dashboard-crm-earning-reports-yearly-overview',
      '/dashboard/CrmEarningReportsYearlyOverview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard-crm-order-bar-chart': RouteRecordInfo<
      'dashboard-crm-order-bar-chart',
      '/dashboard/CrmOrderBarChart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard-crm-project-status': RouteRecordInfo<
      'dashboard-crm-project-status',
      '/dashboard/CrmProjectStatus',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard-crm-recent-transactions': RouteRecordInfo<
      'dashboard-crm-recent-transactions',
      '/dashboard/CrmRecentTransactions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard-crm-revenue-growth': RouteRecordInfo<
      'dashboard-crm-revenue-growth',
      '/dashboard/CrmRevenueGrowth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard-crm-sales-area-charts': RouteRecordInfo<
      'dashboard-crm-sales-area-charts',
      '/dashboard/CrmSalesAreaCharts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard-crm-sales-by-countries': RouteRecordInfo<
      'dashboard-crm-sales-by-countries',
      '/dashboard/CrmSalesByCountries',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard-crm-sessions-bar-with-gap-charts': RouteRecordInfo<
      'dashboard-crm-sessions-bar-with-gap-charts',
      '/dashboard/CrmSessionsBarWithGapCharts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard-saas': RouteRecordInfo<
      'dashboard-saas',
      '/dashboard-saas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard-saas-crm-active-project': RouteRecordInfo<
      'dashboard-saas-crm-active-project',
      '/dashboard-saas/CrmActiveProject',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard-saas-crm-activity-timeline': RouteRecordInfo<
      'dashboard-saas-crm-activity-timeline',
      '/dashboard-saas/CrmActivityTimeline',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard-saas-crm-analytics-sales': RouteRecordInfo<
      'dashboard-saas-crm-analytics-sales',
      '/dashboard-saas/CrmAnalyticsSales',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard-saas-crm-earning-reports-yearly-overview': RouteRecordInfo<
      'dashboard-saas-crm-earning-reports-yearly-overview',
      '/dashboard-saas/CrmEarningReportsYearlyOverview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard-saas-crm-order-bar-chart': RouteRecordInfo<
      'dashboard-saas-crm-order-bar-chart',
      '/dashboard-saas/CrmOrderBarChart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard-saas-crm-project-status': RouteRecordInfo<
      'dashboard-saas-crm-project-status',
      '/dashboard-saas/CrmProjectStatus',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard-saas-crm-recent-transactions': RouteRecordInfo<
      'dashboard-saas-crm-recent-transactions',
      '/dashboard-saas/CrmRecentTransactions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard-saas-crm-revenue-growth': RouteRecordInfo<
      'dashboard-saas-crm-revenue-growth',
      '/dashboard-saas/CrmRevenueGrowth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard-saas-crm-sales-area-charts': RouteRecordInfo<
      'dashboard-saas-crm-sales-area-charts',
      '/dashboard-saas/CrmSalesAreaCharts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard-saas-crm-sales-by-countries': RouteRecordInfo<
      'dashboard-saas-crm-sales-by-countries',
      '/dashboard-saas/CrmSalesByCountries',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard-saas-crm-sessions-bar-with-gap-charts': RouteRecordInfo<
      'dashboard-saas-crm-sessions-bar-with-gap-charts',
      '/dashboard-saas/CrmSessionsBarWithGapCharts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'documentosdian': RouteRecordInfo<
      'documentosdian',
      '/documentosdian',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'documentosdian-notes': RouteRecordInfo<
      'documentosdian-notes',
      '/documentosdian/notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'documentosdian-payroll': RouteRecordInfo<
      'documentosdian-payroll',
      '/documentosdian/payroll',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'documentosdian-support': RouteRecordInfo<
      'documentosdian-support',
      '/documentosdian/support',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'facturas': RouteRecordInfo<
      'facturas',
      '/facturas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'facturas-consultas': RouteRecordInfo<
      'facturas-consultas',
      '/facturas/consultas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'forgot-password': RouteRecordInfo<
      'forgot-password',
      '/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'infodianreal-cargar': RouteRecordInfo<
      'infodianreal-cargar',
      '/infodianreal/cargar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'infodianreal-cargardetalle': RouteRecordInfo<
      'infodianreal-cargardetalle',
      '/infodianreal/cargardetalle',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'infodianreal-enviados': RouteRecordInfo<
      'infodianreal-enviados',
      '/infodianreal/enviados',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'infodianreal-enviados1': RouteRecordInfo<
      'infodianreal-enviados1',
      '/infodianreal/enviados_1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'infodianreal-estadisticaanual': RouteRecordInfo<
      'infodianreal-estadisticaanual',
      '/infodianreal/estadisticaanual',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'infodianreal-procesariva': RouteRecordInfo<
      'infodianreal-procesariva',
      '/infodianreal/procesariva',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'infodianreal-recepcion': RouteRecordInfo<
      'infodianreal-recepcion',
      '/infodianreal/recepcion',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'infodianreal-recibidos': RouteRecordInfo<
      'infodianreal-recibidos',
      '/infodianreal/recibidos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'infodianreal-validarfacturas': RouteRecordInfo<
      'infodianreal-validarfacturas',
      '/infodianreal/validarfacturas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'inicio': RouteRecordInfo<
      'inicio',
      '/inicio',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'inventories': RouteRecordInfo<
      'inventories',
      '/Inventories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'login': RouteRecordInfo<
      'login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'products': RouteRecordInfo<
      'products',
      '/products',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'recepciondefacturas': RouteRecordInfo<
      'recepciondefacturas',
      '/recepciondefacturas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'register': RouteRecordInfo<
      'register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'second-page': RouteRecordInfo<
      'second-page',
      '/second-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'suppliers': RouteRecordInfo<
      'suppliers',
      '/suppliers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'users': RouteRecordInfo<
      'users',
      '/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'users-userssaas': RouteRecordInfo<
      'users-userssaas',
      '/users/userssaas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'resources/ts/pages/index.vue': {
      routes:
        | 'root'
      views:
        | never
    }
    'resources/ts/pages/[...error].vue': {
      routes:
        | '$error'
      views:
        | never
    }
    'resources/ts/pages/balances/index.vue': {
      routes:
        | 'balances'
      views:
        | never
    }
    'resources/ts/pages/companies/index.vue': {
      routes:
        | 'companies'
      views:
        | never
    }
    'resources/ts/pages/control/index.vue': {
      routes:
        | 'control'
      views:
        | never
    }
    'resources/ts/pages/customers/index.vue': {
      routes:
        | 'customers'
      views:
        | never
    }
    'resources/ts/pages/dashboard/index.vue': {
      routes:
        | 'dashboard'
      views:
        | never
    }
    'resources/ts/pages/dashboard/CrmActiveProject.vue': {
      routes:
        | 'dashboard-crm-active-project'
      views:
        | never
    }
    'resources/ts/pages/dashboard/CrmActivityTimeline.vue': {
      routes:
        | 'dashboard-crm-activity-timeline'
      views:
        | never
    }
    'resources/ts/pages/dashboard/CrmAnalyticsSales.vue': {
      routes:
        | 'dashboard-crm-analytics-sales'
      views:
        | never
    }
    'resources/ts/pages/dashboard/CrmEarningReportsYearlyOverview.vue': {
      routes:
        | 'dashboard-crm-earning-reports-yearly-overview'
      views:
        | never
    }
    'resources/ts/pages/dashboard/CrmOrderBarChart.vue': {
      routes:
        | 'dashboard-crm-order-bar-chart'
      views:
        | never
    }
    'resources/ts/pages/dashboard/CrmProjectStatus.vue': {
      routes:
        | 'dashboard-crm-project-status'
      views:
        | never
    }
    'resources/ts/pages/dashboard/CrmRecentTransactions.vue': {
      routes:
        | 'dashboard-crm-recent-transactions'
      views:
        | never
    }
    'resources/ts/pages/dashboard/CrmRevenueGrowth.vue': {
      routes:
        | 'dashboard-crm-revenue-growth'
      views:
        | never
    }
    'resources/ts/pages/dashboard/CrmSalesAreaCharts.vue': {
      routes:
        | 'dashboard-crm-sales-area-charts'
      views:
        | never
    }
    'resources/ts/pages/dashboard/CrmSalesByCountries.vue': {
      routes:
        | 'dashboard-crm-sales-by-countries'
      views:
        | never
    }
    'resources/ts/pages/dashboard/CrmSessionsBarWithGapCharts.vue': {
      routes:
        | 'dashboard-crm-sessions-bar-with-gap-charts'
      views:
        | never
    }
    'resources/ts/pages/dashboard-saas/index.vue': {
      routes:
        | 'dashboard-saas'
      views:
        | never
    }
    'resources/ts/pages/dashboard-saas/CrmActiveProject.vue': {
      routes:
        | 'dashboard-saas-crm-active-project'
      views:
        | never
    }
    'resources/ts/pages/dashboard-saas/CrmActivityTimeline.vue': {
      routes:
        | 'dashboard-saas-crm-activity-timeline'
      views:
        | never
    }
    'resources/ts/pages/dashboard-saas/CrmAnalyticsSales.vue': {
      routes:
        | 'dashboard-saas-crm-analytics-sales'
      views:
        | never
    }
    'resources/ts/pages/dashboard-saas/CrmEarningReportsYearlyOverview.vue': {
      routes:
        | 'dashboard-saas-crm-earning-reports-yearly-overview'
      views:
        | never
    }
    'resources/ts/pages/dashboard-saas/CrmOrderBarChart.vue': {
      routes:
        | 'dashboard-saas-crm-order-bar-chart'
      views:
        | never
    }
    'resources/ts/pages/dashboard-saas/CrmProjectStatus.vue': {
      routes:
        | 'dashboard-saas-crm-project-status'
      views:
        | never
    }
    'resources/ts/pages/dashboard-saas/CrmRecentTransactions.vue': {
      routes:
        | 'dashboard-saas-crm-recent-transactions'
      views:
        | never
    }
    'resources/ts/pages/dashboard-saas/CrmRevenueGrowth.vue': {
      routes:
        | 'dashboard-saas-crm-revenue-growth'
      views:
        | never
    }
    'resources/ts/pages/dashboard-saas/CrmSalesAreaCharts.vue': {
      routes:
        | 'dashboard-saas-crm-sales-area-charts'
      views:
        | never
    }
    'resources/ts/pages/dashboard-saas/CrmSalesByCountries.vue': {
      routes:
        | 'dashboard-saas-crm-sales-by-countries'
      views:
        | never
    }
    'resources/ts/pages/dashboard-saas/CrmSessionsBarWithGapCharts.vue': {
      routes:
        | 'dashboard-saas-crm-sessions-bar-with-gap-charts'
      views:
        | never
    }
    'resources/ts/pages/documentosdian/index.vue': {
      routes:
        | 'documentosdian'
      views:
        | never
    }
    'resources/ts/pages/documentosdian/notes.vue': {
      routes:
        | 'documentosdian-notes'
      views:
        | never
    }
    'resources/ts/pages/documentosdian/payroll.vue': {
      routes:
        | 'documentosdian-payroll'
      views:
        | never
    }
    'resources/ts/pages/documentosdian/support.vue': {
      routes:
        | 'documentosdian-support'
      views:
        | never
    }
    'resources/ts/pages/facturas/index.vue': {
      routes:
        | 'facturas'
      views:
        | never
    }
    'resources/ts/pages/facturas/consultas.vue': {
      routes:
        | 'facturas-consultas'
      views:
        | never
    }
    'resources/ts/pages/forgot-password.vue': {
      routes:
        | 'forgot-password'
      views:
        | never
    }
    'resources/ts/pages/infodianreal/cargar.vue': {
      routes:
        | 'infodianreal-cargar'
      views:
        | never
    }
    'resources/ts/pages/infodianreal/cargardetalle.vue': {
      routes:
        | 'infodianreal-cargardetalle'
      views:
        | never
    }
    'resources/ts/pages/infodianreal/enviados.vue': {
      routes:
        | 'infodianreal-enviados'
      views:
        | never
    }
    'resources/ts/pages/infodianreal/enviados_1.vue': {
      routes:
        | 'infodianreal-enviados1'
      views:
        | never
    }
    'resources/ts/pages/infodianreal/estadisticaanual.vue': {
      routes:
        | 'infodianreal-estadisticaanual'
      views:
        | never
    }
    'resources/ts/pages/infodianreal/procesariva.vue': {
      routes:
        | 'infodianreal-procesariva'
      views:
        | never
    }
    'resources/ts/pages/infodianreal/recepcion.vue': {
      routes:
        | 'infodianreal-recepcion'
      views:
        | never
    }
    'resources/ts/pages/infodianreal/recibidos.vue': {
      routes:
        | 'infodianreal-recibidos'
      views:
        | never
    }
    'resources/ts/pages/infodianreal/validarfacturas.vue': {
      routes:
        | 'infodianreal-validarfacturas'
      views:
        | never
    }
    'resources/ts/pages/inicio/index.vue': {
      routes:
        | 'inicio'
      views:
        | never
    }
    'resources/ts/pages/Inventories/index.vue': {
      routes:
        | 'inventories'
      views:
        | never
    }
    'resources/ts/pages/login.vue': {
      routes:
        | 'login'
      views:
        | never
    }
    'resources/ts/pages/products/index.vue': {
      routes:
        | 'products'
      views:
        | never
    }
    'resources/ts/pages/recepciondefacturas/index.vue': {
      routes:
        | 'recepciondefacturas'
      views:
        | never
    }
    'resources/ts/pages/register.vue': {
      routes:
        | 'register'
      views:
        | never
    }
    'resources/ts/pages/second-page.vue': {
      routes:
        | 'second-page'
      views:
        | never
    }
    'resources/ts/pages/suppliers/index.vue': {
      routes:
        | 'suppliers'
      views:
        | never
    }
    'resources/ts/pages/users/index.vue': {
      routes:
        | 'users'
      views:
        | never
    }
    'resources/ts/pages/users/userssaas.vue': {
      routes:
        | 'users-userssaas'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
